### ISSUE TITLE
Decision tree predict_proba has missing arguments

### ISSUE THREAD

**Issue by javicid** [bsc-wdc/dislib#114]
**Describe the bug**
predict_proba fails if lines 215-219 are executed because predict_proba calls are missing the n_classes argument.

**To Reproduce**
Not sure how to force the algorithm to go through this execution path, but the current tests do not cover it. I guess adding n_classes in lines 217 and 218 should solve the issue.

The error trace is the following:

`Traceback (most recent call last):
  File "/apps/COMPSs/TrunkJAC/Bindings/python/3/pycompss/worker/worker_commons.py", line 321, in execute_task
    new_types, new_values, is_modifier = task_execution_1()
  File "/apps/COMPSs/TrunkJAC/Bindings/python/3/pycompss/worker/worker_commons.py", line 315, in task_execution_1
    return task_execution(logger, process_name, module, method_name, types, values, compss_kwargs)
  File "/apps/COMPSs/TrunkJAC/Bindings/python/3/pycompss/worker/worker_commons.py", line 186, in task_execution
    task_output = getattr(module, method_name)(*values, compss_types=types, **compss_kwargs)
  File "/apps/COMPSs/TrunkJAC/Bindings/python/3/pycompss/api/task.py", line 229, in task_decorator
    return self.worker_call(*args, **kwargs)
  File "/apps/COMPSs/TrunkJAC/Bindings/python/3/pycompss/api/task.py", line 874, in worker_call
    user_returns = self.user_function(*user_args, **user_kwargs)
  File "/gpfs/home/bsc19/bsc19150/dislib/dislib/classification/rf/decision_tree.py", line 488, in _predict_branch_proba
    prediction = subtree.predict_proba(samples[indices_mask], n_classes)
  File "/gpfs/home/bsc19/bsc19150/dislib/dislib/classification/rf/decision_tree.py", line 217, in predict_proba
    pred[left_mask] = self.left.predict_proba(sample[left_mask])
TypeError: predict_proba() missing 1 required positional argument: 'n_classes'`

**Comment by salvisolamartinell** [comment]
Decision tree predict_proba was not working if while building it the `use_sklearn and n_features * len(sample) <= sklearn_max` of the _compute_build_subtree method was False. On practice, `use_sklearn=True` and `sklearn_max=1e8` is hardcoded, so this condition was only triggered for big datasets and it hadn't been tested.
#123 fixes this, but tests should be added somehow
